---
title: "Word Prediction Pitch"
author: "refreform"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

## Predict-a-Word Instructions

To use the Predict-a-Word simply type in an incomplete sentence and the 
predicted word will appear on the right. It's that simple! Wow!

## The Algorithm Explained

The algorithm is actually quite simple, and depends heavily on the .csv file
provided. The csv file in this case is generated by the Model Code.R file found
in this repo. It samples the three txt files provided, and then outputs a csv of
the best prediction for each word, depending on what was most used. It also 
calculates the most commonly applicable word, which is "the" so if the last word
cannot be found it uses the word "the" as a default as that is the most commonly
applicable word. It does also check to see if anything has been typed, and if 
nothing has been typed nothing is predicted. (See code on next slide)

## Algorithm Code

```{r algorithm}
#  corpus_table <- read.csv('nextword.csv')

#    output$prediction <- renderText({
#      req(input$sentence)
#      sentence<-input$sentence
#      last_word <- sub("^.*\\s+(\\S+)$", "\\1", tolower(input$sentence))
#      last_word <- sub("\\s+$", "", last_word)
#      prediction <- corpus_table$nex[corpus_table$prev == last_word]
#      if (is.na(prediction) || length(prediction) == 0) {
#        "the"
#      } else prediction
#    })
```

## Why this approach?

I took this approach as is is extremely efficient computationally, as all 
combinations are previously computed and the response is lightning fast, not 
even requiring an input button, which is my use case. This is more similar to 
auto-correct/ predict on your phone. Hence, large complex models are less ideal.
Matching 2 or 3 deep ngrams can be computationally intensive, and while they
do provide better results, where not chosen due to the necessity of speed.

## Future Plans 

I intend to make a program to look at housing market by scraping Zillow,
and then predict what some house may cost based on number of bedrooms, sqft,
bathrooms, etc, and (more ambitiously) look into the predictive factors of
fertility. Stay tuned!
